FROM centos:7

EXPOSE 389 636


RUN yum update -y && \
    yum install openldap-servers openldap-clients openssl vim -y && \
    yum clean all


COPY files /files/
RUN chmod 755 /files/entrypoint.sh
VOLUME [ "/var/lib/ldap", "/etc/openldap" ]
ENTRYPOINT ["/files/entrypoint.sh"]

